version: '3.8'

services:
  authproxy:
    build:
      context: ./microservices/authproxy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8083:8083"
    networks:
      - intern-network
    profiles:
      - local
      - deploy

  request-sync:
    build:
      context: ./microservices/request-sync
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - intern-network
    profiles:
      - local
      - deploy

  calculation_unit:
    build:
      context: ./microservices/calculation_unit
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - intern-network
    profiles:
      - local
      - deploy

  mongodb:
    image: mongo:latest
    container_name: mongodb-projekt
    ports:
      - "27017:27017"
    networks:
      - intern-network
    profiles:
      - local
      - deploy

networks:
  intern-network:
    driver: bridge
