version: '3.8'

services:
  authproxy:
    build:
      context: ./microservices/authproxy
      dockerfile: Dockerfile
    image: authproxy
    ports:
      - "8080:8080"
      - "8083:8083"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  3d-calculation_unit:
    build:
      context: ./microservices/calculation_unit
      dockerfile: Dockerfile
    image: 3d-calculation-unit
    environment:
      - SERVICE_PORT=8090
    networks:
      - sose25-projekt
    ports:
      - "8090:8090"

  pong-calculation_unit:
    build:
      context: ./microservices
      dockerfile: pong/Dockerfile
    image: pong-calculation-unit
    environment:
      - SERVICE_PORT=8090
    networks:
      - sose25-projekt
    ports:
      - "8090:8090"

  mongodb:
    image: mongo:latest
    container_name: mongodb-projekt
    ports:
      - "27017:27017"

networks:
  sose25-projekt:
    driver: bridge
