version: '3.8'

services:
  authproxy:
    build:
      context: ./microservices/authproxy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8083:8083"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  calculation_unit:
    build:
      context: ./microservices/calculation_unit
      dockerfile: Dockerfile
    environment:
      - SERVICE_PORT=8090
    ports:
      - "8090:8090"

  mongodb:
    image: mongo:latest
    container_name: mongodb-projekt
    ports:
      - "27017:27017"
