version: '3.8'

services:
  authproxy:
    build:
      context: ./microservices/authproxy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8083:8083"

  calculation_unit_1:
    build:
      context: ./microservices/calculation_unit
      dockerfile: Dockerfile
    ports:
      - "8090:8090"

  calculation_unit_2:
    build:
      context: ./microservices/calculation_unit
      dockerfile: Dockerfile
    ports:
      - "8091:8091"

  calculation_unit_3:
    build:
      context: ./microservices/calculation_unit
      dockerfile: Dockerfile
    ports:
      - "8092:8092"



  mongodb:
    image: mongo:latest
    container_name: mongodb-projekt
    ports:
      - "27017:27017"
