services:
  authproxy:
    build:
      context: ./microservices/authproxy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  request-sync:
    build:
      context: ./microservices/request-sync
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  calculation_unit:
    build:
      context: ./microservices/calculation_unit
      dockerfile: dockerfile
    ports:
      - "8082:8082"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
