services:
  authproxy:
    build:
      context: ./microservices/authproxy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - intern-network

  request-sync:
    build:
      context: ./microservices/request-sync
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - intern-network

  calculation_unit:
    build:
      context: ./microservices/calculation_unit
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - intern-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - intern-network

networks:
  intern-network:
    driver: bridge
