version: '3.8'

services:
  authproxy:
    build:
      context: ./microservices/authproxy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8083:8083"

  calculation_unit_1:
    build:
      context: ./microservices/calculation_unit
      dockerfile: Dockerfile
    environment:
      - SERVICE_PORT=8090
    ports:
      - "8090:8090"

  calculation_unit_2:
    build:
      context: ./microservices/calculation_unit
      dockerfile: Dockerfile
    environment:
      - SERVICE_PORT=8091
    ports:
      - "8091:8091"

  playtest_calculation_unit_1:
    build:
      context: ./microservices/playtest_calculation_unit
      dockerfile: Dockerfile
    environment:
      - SERVICE_PORT=9100
    ports:
      - "9100:9100"

  playtest_calculation_unit_2:
    build:
      context: ./microservices/playtest_calculation_unit
      dockerfile: Dockerfile
    environment:
      - SERVICE_PORT=9101
    ports:
      - "9101:9101"

  mongodb:
    image: mongo:latest
    container_name: mongodb-projekt
    ports:
      - "27017:27017"
