
#ifndef CORE_CONFIG_HEADER
#define CORE_CONFIG_HEADER


// blitter
#define FRAME_RESOLUTION_X 1600
#define FRAME_RESOLUTION_Y 900
#define FRAME_TIME_BUDGET_MS 15.

#define BUFFER_MAXIMUM_TEXTURE_COUNT 1024
#define BUFFER_ATLAS_BORDER_PADDING 32

// renderer
#define RENDERER_SPRITE_MEMORY_WIDTH 15000
#define RENDERER_SPRITE_MEMORY_HEIGHT 15000
#define RENDERER_FONT_MEMORY_WIDTH 5000
#define RENDERER_FONT_MEMORY_HEIGHT 5000
#define RENDERER_MAXIMUM_FONT_COUNT 2

// network
#define NETWORK_HOST "ec2-3-124-115-76.eu-central-1.compute.amazonaws.com"
#define NETWORK_PORT_ADAPTER "8080"
#define NETWORK_PORT_WEBSOCKET "8083"
#define NETWORK_CONNECTION_STALL 500
#define NETWORK_CALCULATION_FRAMES 60

#define FEAT_MULTIPLAYER 1

// TODO define in extern config file and store constants at runtime


#endif
