name: Deploy to AWS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Setze Berechtigungen install-server-dependencies.sh
        run: chmod +x ./infrastructure/main/install-server-dependencies.sh

      - name: Check if server has everything installed
        run: ./infrastructure/main/install-server-dependencies.sh
